https://cdn.jsdelivr.net/gh/OpiumBest/svg/icon.svg
https://quantil.jsdelivr.net/gh/OpiumBest/svg/icon.svg
https://gcore.jsdelivr.net/gh/OpiumBest/svg/icon.svg
https://s3.amazonaws.com/cleverlearning/icon.svg
https://storage.googleapis.com/gclassroom/icon.svg
https://opiumbest.github.io/
https://jsdelivr.b-cdn.net/gh/OpiumBest/svg/icon.svg
https://cdn.statically.io/gh/OpiumBest/svg@main/icon.svg
https://raw.esm.sh/gh/OpiumBest/svg/icon.svg
https://cleverlearning.s3.amazonaws.com/icon.svg
